
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// BLOCK
export const CREATE_BLOCK_SUCCESS = "CREATE_BLOCK_SUCCESS";
export const DELETE_BLOCK_SUCCESS = "DELETE_BLOCK_SUCCESS";
export const GET_BLOCK_SUCCESS = "GET_BLOCK_SUCCESS";
export const LIST_BLOCK_SUCCESS = "LIST_BLOCK_SUCCESS";
export const UPDATE_BLOCK_SUCCESS = "UPDATE_BLOCK_SUCCESS";

// BLOCKTYPE
export const CREATE_BLOCKTYPE_SUCCESS = "CREATE_BLOCKTYPE_SUCCESS";
export const DELETE_BLOCKTYPE_SUCCESS = "DELETE_BLOCKTYPE_SUCCESS";
export const FINDBYNAME_BLOCKTYPE_SUCCESS = "FINDBYNAME_BLOCKTYPE_SUCCESS";
export const GET_BLOCKTYPE_SUCCESS = "GET_BLOCKTYPE_SUCCESS";
export const LIST_BLOCKTYPE_SUCCESS = "LIST_BLOCKTYPE_SUCCESS";
export const UPDATE_BLOCKTYPE_SUCCESS = "UPDATE_BLOCKTYPE_SUCCESS";

// ITEM
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const FINDBYTYPE_ITEM_SUCCESS = "FINDBYTYPE_ITEM_SUCCESS";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GETLINK_ITEM_SUCCESS = "GETLINK_ITEM_SUCCESS";
export const GETLINK_ITEM_SUCCESS = "GETLINK_ITEM_SUCCESS";
export const LIST_ITEM_SUCCESS = "LIST_ITEM_SUCCESS";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";

// ROLE
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const LIST_ROLE_SUCCESS = "LIST_ROLE_SUCCESS";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";

// STATUS

// TYPE
export const CREATE_TYPE_SUCCESS = "CREATE_TYPE_SUCCESS";
export const DELETE_TYPE_SUCCESS = "DELETE_TYPE_SUCCESS";
export const FINDBYNAME_TYPE_SUCCESS = "FINDBYNAME_TYPE_SUCCESS";
export const GET_TYPE_SUCCESS = "GET_TYPE_SUCCESS";
export const LIST_TYPE_SUCCESS = "LIST_TYPE_SUCCESS";
export const UPDATE_TYPE_SUCCESS = "UPDATE_TYPE_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
